-- Level 1 - Very Basic SELECT Queries
-- 1. Show all customers
SELECT *
FROM customer_info;

-- 2. Show only customer first names and emails
SELECT first_name, email
from customer_info;

-- 3. Show all products with sale price greater than 500
SELECT product_name, sale_price
from product_info
where sale_price > 500;

-- 4. Show stores located in Maharashtra
SELECT store_name, state
from branch_details
where state = 'Maharashtra';


-- 5. Show unique product categories
SELECT DISTINCT product_category
from product_info;

-- Level 2 — Sorting and Filtering
-- 6. Show products sorted by highest sale price
select product_name, sale_price
from product_info
order by sale_price DESC;

-- 7. Show top 5 expensive products
select product_name, sale_price
from product_info
ORDER by sale_price DESC limit 5;



-- 8. Find customers whose first name starts with 'A'
select first_name
from customer_info
where first_name like 'A%';


-- Level 3 — Aggregate Functions
-- 9. Find total number of customers
select count(customer_id)
from customer_info;

-- 10. Find average sale price of products
SELECT  round(AVG(sale_price),2)
from product_info;

-- 11. Find maximum and minimum sale price
select min(sale_price), max(sale_price)
from product_info;

-- Level 4 — GROUP BY
-- 12. Count products in each category
select distinct product_category, count(product_id)
from product_info
group by product_category;

-- 13. Find average sale price by category
select product_category, round(avg(sale_price),2)
from product_info
group by product_category;

-- Level 5 — Basic JOINS
-- 14. Show orders with customer names
select op.order_id, ci.first_name, ci.last_name, sf.order_date
from order_product_mapping as op
join sales_fact as sf on op.order_id = sf.order_id
join customer_info as ci on sf.customer_id = ci.customer_id;

-- 15. Show orders with branch/store names
select op.order_id, bd.store_name, bd.area, sf.order_date
from order_product_mapping as op
join sales_fact as sf on op.order_id = sf.order_id
join customer_info as ci on sf.customer_id = ci.customer_id
join branch_details as bd on bd.store_id = sf.store_id;

-- 16. Show ordered products with quantity
select pi.product_id, pi.product_name, op.quantity_ordered
from order_product_mapping as op
join product_info as pi on op.product_id = pi.product_id;


-- Level 6 — Multi-table JOINS
-- 17. Show customer name, product name, and quantity ordered
select ci.first_name, ci.last_name, pi.product_name , sum(quantity_ordered)
from order_product_mapping as op
join sales_fact as sf on op.order_id = sf.order_id
join customer_info as ci on sf.customer_id = ci.customer_id
join product_info as pi on  pi.product_id = op.product_id
group by ci.first_name, ci.last_name, pi.product_name;

-- 18. Find total sales amount for each order
select op.order_id, sum(op.quantity_ordered*pi.sale_price)
from order_product_mapping as op
join sales_fact as sf on op.order_id = sf.order_id
join customer_info as ci on sf.customer_id = ci.customer_id
join product_info as pi on  pi.product_id = op.product_id
group by op.order_id;

-- Level 7 — Business Analysis Queries
-- 19. Find total revenue generated by each product
select pi.product_name, sum(op.quantity_ordered*pi.sale_price) AS revenue
from order_product_mapping as op
join sales_fact as sf on op.order_id = sf.order_id
join customer_info as ci on sf.customer_id = ci.customer_id
join product_info as pi on  pi.product_id = op.product_id
group by pi.product_name
ORDER BY revenue DESC;

-- 20. Find top 5 customers by total spending
select ci.first_name, ci.last_name, sum(quantity_ordered * sale_price) as Total_Spending
from customer_info as ci
join sales_fact as sf on ci.customer_id = sf.customer_id
join order_product_mapping as op on op.order_id = sf.order_id
join product_info as pi on pi.product_id = op.product_id
group by ci.first_name, ci.last_name
order by Total_Spending DESC
limit 5;

-- 21. Find total revenue generated by each store

select bd.store_name, bd.area, sum(quantity_ordered * sale_price) as revenue
from branch_details as bd
join sales_fact as sf on bd.store_id = sf.store_id
join order_product_mapping as op on op.order_id = sf.order_id
join product_info as pi on pi.product_id = op.product_id
group by bd.store_name, bd.area
order by revenue DESC;

-- Level 8 — Important Practice Questions
-- 22. Find customers who never placed any order





-- 23. Find products never ordered






-- 24. Find month-wise sales






-- 25. Find highest selling product